on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Desired release version tag (e.g. v0.4.0-rc.0)'
        required: true

jobs:
  release_apiserver:
    env:
      working-directory: ./apiserver
    name: Release APIServer Docker Image
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Default value should work for both pull_request and merge(push) event.
          ref: ${{github.event.pull_request.head.sha}}

      - name: install kubebuilder
        run: |
          wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
          sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

      - name: Get revision SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get dependencies
        run: go mod download
        working-directory: ${{env.working-directory}}

      - name: Build
        run: go build ./...
        working-directory: ${{env.working-directory}}

      - name: Test
        run: go test ./...
        working-directory: ${{env.working-directory}}

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build Docker Image - Apiserver
        run: |
          docker build -t kuberay/apiserver:${{ steps.vars.outputs.sha_short }} -f apiserver/Dockerfile .
          docker save -o /tmp/apiserver.tar kuberay/apiserver:${{ steps.vars.outputs.sha_short }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: contains(fromJson('["refs/heads/master", "refs/heads/release-0.3"]'), github.ref)

      - name: Push Apiserver to DockerHub
        run: |
          docker push kuberay/apiserver:${{ steps.vars.outputs.sha_short }};
          docker image tag kuberay/apiserver:${{ steps.vars.outputs.sha_short }} kuberay/apiserver:${{ github.event.inputs.tag }};
          docker push kuberay/apiserver:${{ github.event.inputs.tag }}

  build_operator:
    env:
      working-directory: ./ray-operator
    name: Build Operator Docker Images
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Default value should work for both pull_request and merge(push) event.
        ref: ${{github.event.pull_request.head.sha}}

    - name: install kubebuilder
      run: |
        wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.0.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        sudo mv kubebuilder_$(go env GOOS)_$(go env GOARCH) /usr/local/bin/kubebuilder

    - name: Get revision SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get dependencies
      run: go mod download
      working-directory: ${{env.working-directory}}

    - name: Build
      run: make build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: make test
      working-directory: ${{env.working-directory}}

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Build Docker Image - Operator
      run: |
        IMG=kuberay/operator:${{ steps.vars.outputs.sha_short }} make docker-image
      working-directory: ${{env.working-directory}}

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: contains(fromJson('["refs/heads/master", "refs/heads/release-0.3"]'), github.ref)

    - name: Push Operator to DockerHub
      run: |
        docker push kuberay/operator:${{ steps.vars.outputs.sha_short }};
        docker image tag kuberay/operator:${{ steps.vars.outputs.sha_short }} kuberay/operator:${{ github.event.inputs.tag }};
        docker push kuberay/operator:${{ github.event.inputs.tag }}

      working-directory: ${{env.working-directory}}
